/**
 * Validates the AI's output against the original text to prevent hallucinations.
 * @param {string} rawText The original source text from the report.
 * @param {Array} normalizedTests The array of test objects generated by the AI.
 * @returns {boolean} Returns true if all tests are valid, false otherwise.
 */
exports.validateTests = (rawText, normalizedTests) => {
  console.log('Validating AI output against source text...');

  const sourceText = rawText.toLowerCase();

  for (const test of normalizedTests) {
    const testName = test.name.toLowerCase();

    if (!sourceText.includes(testName)) {
      console.error(`Validation FAILED: AI hallucinated test "${test.name}".`);
      return false;
    }
  }

  console.log('Validation successful. All tests are present in the source text.');
  return true;
};